// Copyright © 2025 Prabhjot Singh Sethi, All Rights reserved
// Author: Prabhjot Singh Sethi <prabhjot.sethi@gmail.com>

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: ip-location.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IpLocation_GetLocation_FullMethodName = "/api.IpLocation/GetLocation"
)

// IpLocationClient is the client API for IpLocation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IP Location service provided over gRPC
type IpLocationClient interface {
	GetLocation(ctx context.Context, in *LocationReq, opts ...grpc.CallOption) (*LocationResp, error)
}

type ipLocationClient struct {
	cc grpc.ClientConnInterface
}

func NewIpLocationClient(cc grpc.ClientConnInterface) IpLocationClient {
	return &ipLocationClient{cc}
}

func (c *ipLocationClient) GetLocation(ctx context.Context, in *LocationReq, opts ...grpc.CallOption) (*LocationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LocationResp)
	err := c.cc.Invoke(ctx, IpLocation_GetLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IpLocationServer is the server API for IpLocation service.
// All implementations must embed UnimplementedIpLocationServer
// for forward compatibility.
//
// IP Location service provided over gRPC
type IpLocationServer interface {
	GetLocation(context.Context, *LocationReq) (*LocationResp, error)
	mustEmbedUnimplementedIpLocationServer()
}

// UnimplementedIpLocationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIpLocationServer struct{}

func (UnimplementedIpLocationServer) GetLocation(context.Context, *LocationReq) (*LocationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocation not implemented")
}
func (UnimplementedIpLocationServer) mustEmbedUnimplementedIpLocationServer() {}
func (UnimplementedIpLocationServer) testEmbeddedByValue()                    {}

// UnsafeIpLocationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IpLocationServer will
// result in compilation errors.
type UnsafeIpLocationServer interface {
	mustEmbedUnimplementedIpLocationServer()
}

func RegisterIpLocationServer(s grpc.ServiceRegistrar, srv IpLocationServer) {
	// If the following call pancis, it indicates UnimplementedIpLocationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IpLocation_ServiceDesc, srv)
}

func _IpLocation_GetLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpLocationServer).GetLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IpLocation_GetLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpLocationServer).GetLocation(ctx, req.(*LocationReq))
	}
	return interceptor(ctx, in, info, handler)
}

// IpLocation_ServiceDesc is the grpc.ServiceDesc for IpLocation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IpLocation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.IpLocation",
	HandlerType: (*IpLocationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLocation",
			Handler:    _IpLocation_GetLocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ip-location.proto",
}
