// Copyright © 2025 Prabhjot Singh Sethi, All Rights reserved
// Author: Prabhjot Singh Sethi <prabhjot.sethi@gmail.com>

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: ip-location.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationReq) Reset() {
	*x = LocationReq{}
	mi := &file_ip_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationReq) ProtoMessage() {}

func (x *LocationReq) ProtoReflect() protoreflect.Message {
	mi := &file_ip_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationReq.ProtoReflect.Descriptor instead.
func (*LocationReq) Descriptor() ([]byte, []int) {
	return file_ip_location_proto_rawDescGZIP(), []int{0}
}

func (x *LocationReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type LocationResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// latitude of location
	Latitude float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// longitude of location
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// country info
	Country string `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	// region info
	Region string `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	// city
	City string `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	// postal code
	Postal        string `protobuf:"bytes,6,opt,name=postal,proto3" json:"postal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationResp) Reset() {
	*x = LocationResp{}
	mi := &file_ip_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationResp) ProtoMessage() {}

func (x *LocationResp) ProtoReflect() protoreflect.Message {
	mi := &file_ip_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationResp.ProtoReflect.Descriptor instead.
func (*LocationResp) Descriptor() ([]byte, []int) {
	return file_ip_location_proto_rawDescGZIP(), []int{1}
}

func (x *LocationResp) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LocationResp) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *LocationResp) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *LocationResp) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *LocationResp) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *LocationResp) GetPostal() string {
	if x != nil {
		return x.Postal
	}
	return ""
}

var File_ip_location_proto protoreflect.FileDescriptor

const file_ip_location_proto_rawDesc = "" +
	"\n" +
	"\x11ip-location.proto\x12\x03api\"\x1d\n" +
	"\vLocationReq\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"\xa6\x01\n" +
	"\fLocationResp\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x16\n" +
	"\x06postal\x18\x06 \x01(\tR\x06postal2B\n" +
	"\n" +
	"IpLocation\x124\n" +
	"\vGetLocation\x12\x10.api.LocationReq\x1a\x11.api.LocationResp\"\x00B0Z.github.com/go-core-stack/location-services/apib\x06proto3"

var (
	file_ip_location_proto_rawDescOnce sync.Once
	file_ip_location_proto_rawDescData []byte
)

func file_ip_location_proto_rawDescGZIP() []byte {
	file_ip_location_proto_rawDescOnce.Do(func() {
		file_ip_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ip_location_proto_rawDesc), len(file_ip_location_proto_rawDesc)))
	})
	return file_ip_location_proto_rawDescData
}

var file_ip_location_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ip_location_proto_goTypes = []any{
	(*LocationReq)(nil),  // 0: api.LocationReq
	(*LocationResp)(nil), // 1: api.LocationResp
}
var file_ip_location_proto_depIdxs = []int32{
	0, // 0: api.IpLocation.GetLocation:input_type -> api.LocationReq
	1, // 1: api.IpLocation.GetLocation:output_type -> api.LocationResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ip_location_proto_init() }
func file_ip_location_proto_init() {
	if File_ip_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ip_location_proto_rawDesc), len(file_ip_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ip_location_proto_goTypes,
		DependencyIndexes: file_ip_location_proto_depIdxs,
		MessageInfos:      file_ip_location_proto_msgTypes,
	}.Build()
	File_ip_location_proto = out.File
	file_ip_location_proto_goTypes = nil
	file_ip_location_proto_depIdxs = nil
}
